
services:
  calculo-score:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - microservices-network
networks:
  microservices-network:
    external: true
    name: microservices-network