services:
  - type: web
    name: calculo-score-api
    runtime: docker
    buildCommand: docker build -t calculo-score .
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
